In [1]:
# kaggle API를 사용하기 위해 API 키 json 파일 업로드
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"jhw0714","key":"5ebfcd63c0dd4e608eb3f7b6fbbb5ebd"}'}

In [2]:
# kaggle.json 파일을 적절한 디렉토리로 옮긴다.
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# 데이터셋을 다운로드한다.
!kaggle datasets download -d vladimirvorobevv/chatgpt-paraphrases
!unzip -o /content/chatgpt-paraphrases.zip -d /content/sample_data

Downloading chatgpt-paraphrases.zip to /content
100% 60.0M/60.0M [00:04<00:00, 23.1MB/s]
100% 60.0M/60.0M [00:04<00:00, 15.3MB/s]
Archive:  /content/chatgpt-paraphrases.zip
  inflating: /content/sample_data/chatgpt_paraphrases.csv

In [3]:
# 파이스파크 설치
!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq

# 한국어 텍스트 전처리를 도와주는 NLTK 패키지
!pip install nltk

import os
import re
from google.colab import drive
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
drive.mount('/content/drive')

Collecting pyspark
  Downloading pyspark-3.5.0.tar.gz (316.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.9/316.9 MB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.0-py2.py3-none-any.whl size=317425344 sha256=904d260d6ec2013455789c32cb13afd431af11bfa5e7b988fbe85356fd3b1938
  Stored in directory: /root/.cache/pip/wheels/41/4e/10/c2cf2467f71c678cfc8a6b9ac9241e5e44a01940da8fbb17fc
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.0
The following additional packages will be installed:
  libxtst6 openjdk-8-jre-headless
Suggested packages:
  openjdk-8-demo openjdk-8-source libnss-mdns fonts-dejavu-extra fonts-nanum fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-microhei fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  libxtst6 openjdk-8-jdk-headless openjdk-8-jre-headless
0 upgraded, 3 newly installed, 0 to remove and 10 not upgraded.
Need to get 39.7 MB of archives.
After this operation, 144 MB of additional disk space will be used.
Selecting previously unselected package libxtst6:amd64.
(Reading database ... 120880 files and directories currently installed.)
Preparing to unpack .../libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package openjdk-8-jre-headless:amd64.
Preparing to unpack .../openjdk-8-jre-headless_8u382-ga-1~22.04.1_amd64.deb ...
Unpacking openjdk-8-jre-headless:amd64 (8u382-ga-1~22.04.1) ...
Selecting previously unselected package openjdk-8-jdk-headless:amd64.
Preparing to unpack .../openjdk-8-jdk-headless_8u382-ga-1~22.04.1_amd64.deb ...
Unpacking openjdk-8-jdk-headless:amd64 (8u382-ga-1~22.04.1) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up openjdk-8-jre-headless:amd64 (8u382-ga-1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
Setting up openjdk-8-jdk-headless:amd64 (8u382-ga-1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/clhsdb to provide /usr/bin/clhsdb (clhsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/hsdb to provide /usr/bin/hsdb (hsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/idlj to provide /usr/bin/idlj (idlj) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javah to provide /usr/bin/javah (javah) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)
Mounted at /content/drive

In [4]:
# Let's import the libraries we will need
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import pyspark
from pyspark.sql import *
from pyspark.sql.functions import *
# SparkContext is the entry point to any spark functionality.
# SparkConf provides configurations to run a Spark application.
from pyspark import SparkContext, SparkConf

# create the Spark Session
spark = SparkSession.builder.appName("WordCount").getOrCreate()

# create the Spark Context
sc = spark.sparkContext

In [5]:
data=pd.read_csv('/content/sample_data/chatgpt_paraphrases.csv')

In [6]:
# 각 문장을 사람이 작성했는지, AI가 작성했는지 태그
category={}
for i in range(len(data)):
    chatgpt=data.iloc[i]["paraphrases"][1:-1].split(', ')
    for j in chatgpt[:1]:
        category[j[1:-1]]='chatgpt'
    category[data.iloc[i]['text']]="human"

In [7]:
# 사람의 작성한 문장과 AI가 작성한 문장을 분리
total_paraphrases=pd.DataFrame(category.items(),columns=["text","category"])
human_paraphrases = total_paraphrases[total_paraphrases['category'] == 'human']
gpt_paraphrases = total_paraphrases[total_paraphrases['category'] == 'chatgpt']

# 단어의 빈도 수 확인

In [8]:
import nltk

from nltk.corpus import stopwords
nltk.download('stopwords')

use_stopwords = True
english_stop_list = [".", ",", "!", "?", ")", "(", "'", '"', "]", "[", "{", "}", ":", ";", "<", ">", "~", "''", "``"]

if use_stopwords:
  english_stop_list += list(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [9]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.stem import RegexpStemmer
from nltk.stem import WordNetLemmatizer

from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [10]:
from nltk import pos_tag
from nltk.tokenize import word_tokenize
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

# 품사 매뉴얼 출력
nltk.help.upenn_tagset()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package tagsets to /root/nltk_data...

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
JJR: adjective, comparative
    bleaker braver breezier briefer brighter brisker broader bumper busier
    calmer cheaper choosier cleaner clearer closer colder commoner costlier
    cozier creamier crunchier cuter ...
JJS: adjective, superlative
    calmest cheapest choicest classiest cleanest clearest closest commonest
    corniest costliest crassest creepiest crudest cutest darkest deadliest
    dearest deepest densest dinkiest ...
LS: list item marker
    A A. B B. C C. D E F First G H I J K One SP-44001 SP-44002 SP-44005
    SP-44007 Second Third Three Two * a b c d first five four one six three
    two
MD: modal auxiliary
    can cannot could couldn't dare may might must need ought shall should
    shouldn't will would
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...
NNPS: noun, proper, plural
    Americans Americas Amharas Amityvilles Amusements Anarcho-Syndicalists
    Andalusians Andes Andruses Angels Animals Anthony Antilles Antiques
    Apache Apaches Apocrypha ...
NNS: noun, common, plural
    undergraduates scotches bric-a-brac products bodyguards facets coasts
    divestitures storehouses designs clubs fragrances averages
    subjectivists apprehensions muses factory-jobs ...
PDT: pre-determiner
    all both half many quite such sure this
POS: genitive marker
    ' 's
PRP: pronoun, personal
    hers herself him himself hisself it itself me myself one oneself ours
    ourselves ownself self she thee theirs them themselves they thou thy us
PRP$: pronoun, possessive
    her his mine my our ours their thy your
RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
RBR: adverb, comparative
    further gloomier grander graver greater grimmer harder harsher
    healthier heavier higher however larger later leaner lengthier less-
    perfectly lesser lonelier longer louder lower more ...
RBS: adverb, superlative
    best biggest bluntest earliest farthest first furthest hardest
    heartiest highest largest least less most nearest second tightest worst
RP: particle
    aboard about across along apart around aside at away back before behind
    by crop down ever fast for forth from go high i.e. in into just later
    low more off on open out over per pie raising start teeth that through
    under unto up up-pp upon whole with you
SYM: symbol
    % & ' '' ''. ) ). * + ,. < = > @ A[fj] U.S U.S.S.R * ** ***
TO: "to" as preposition or infinitive marker
    to
UH: interjection
    Goodbye Goody Gosh Wow Jeepers Jee-sus Hubba Hey Kee-reist Oops amen
    huh howdy uh dammit whammo shucks heck anyways whodunnit honey golly
    man baby diddle hush sonuvabitch ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...
VBD: verb, past tense
    dipped pleaded swiped regummed soaked tidied convened halted registered
    cushioned exacted snubbed strode aimed adopted belied figgered
    speculated wore appreciated contemplated ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
VBN: verb, past participle
    multihulled dilapidated aerosolized chaired languished panelized used
    experimented flourished imitated reunifed factored condensed sheared
    unsettled primed dubbed desired ...
VBP: verb, present tense, not 3rd person singular
    predominate wrap resort sue twist spill cure lengthen brush terminate
    appear tend stray glisten obtain comprise detest tease attract
    emphasize mold postpone sever return wag ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
WDT: WH-determiner
    that what whatever which whichever
WP: WH-pronoun
    that what whatever whatsoever which who whom whosoever
WP$: WH-pronoun, possessive
    whose
WRB: Wh-adverb
    how however whence whenever where whereby whereever wherein whereof why
``: opening quotation mark
    ` ``

[nltk_data]   Unzipping help/tagsets.zip.

In [11]:
word_list_gpt = []
pos_list_gpt = []
for i in range(gpt_paraphrases.shape[0]):
  sentence_gpt = gpt_paraphrases.iloc[i]['text'].lower()
  sentence_tokens_gpt = word_tokenize(sentence_gpt)
  sentence_pos_gpt = pos_tag(sentence_tokens_gpt)
  for token_word in sentence_tokens_gpt:
    if token_word in english_stop_list:
      sentence_tokens_gpt.remove(token_word)

  pos_list_gpt += sentence_pos_gpt
  word_list_gpt += sentence_tokens_gpt

In [12]:
df_pos_gpt = {'pos': [pos[1] for pos in pos_list_gpt]}
pandas_df_pos_gpt = pd.DataFrame(data=df_pos_gpt)
spark_df_pos_gpt = spark.createDataFrame(pandas_df_pos_gpt)

all_pos_gpt = spark_df_pos_gpt.rdd.map(lambda poslist: (poslist.pos, 1))
all_pos_counts_gpt = all_pos_gpt.reduceByKey(lambda a, b: a+b).sortBy(lambda r: -r[1])
all_pos_counts_gpt.take(10)

[('NN', 1068050),
 ('IN', 575562),
 ('DT', 507743),
 ('JJ', 423269),
 ('NNS', 304373),
 ('.', 278256),
 ('VB', 205065),
 ('VBZ', 176750),
 ('TO', 136835),
 ('VBN', 110508)]

In [13]:
df_gpt = {'word': [lemmatizer.lemmatize(word , pos="v") for word in word_list_gpt]}
pandas_df_gpt = pd.DataFrame(data=df_gpt)
spark_df_gpt = spark.createDataFrame(pandas_df_gpt)

all_words_gpt = spark_df_gpt.rdd.map(lambda words: (words.word, 1))
all_words_counts_gpt = all_words_gpt.reduceByKey(lambda a, b: a+b).sortBy(lambda r: -r[1])
all_words_counts_gpt.take(10)

[('the', 126898),
 ('be', 120713),
 ('a', 57092),
 ("'s", 35939),
 ('you', 24212),
 ('it', 18519),
 ('do', 14347),
 ('reason', 13465),
 ('i', 12294),
 ('ways', 12025)]

In [14]:
word_list_hum = []
pos_list_hum = []
for i in range(human_paraphrases.shape[0]):
  sentence_hum = human_paraphrases.iloc[i]['text'].lower()
  sentence_tokens_hum = word_tokenize(sentence_hum)
  sentence_pos_hum = pos_tag(sentence_tokens_hum)
  for token_word in sentence_tokens_hum:
    if token_word in english_stop_list:
      sentence_tokens_hum.remove(token_word)

  pos_list_hum += sentence_pos_hum
  word_list_hum += sentence_tokens_hum

In [15]:
# 각 단어의 출현 횟수를 센다.
df_hum = {'word': [lemmatizer.lemmatize(word , pos="v") for word in word_list_hum]}
pandas_df_hum = pd.DataFrame(data=df_hum)
spark_df_hum = spark.createDataFrame(pandas_df_hum)

all_words_hum = spark_df_hum.rdd.map(lambda words: (words.word, 1))
all_words_counts_hum = all_words_hum.reduceByKey(lambda a, b: a+b).sortBy(lambda r: -r[1])
all_words_counts_hum.take(10)

[('the', 201229),
 ('be', 140846),
 ('a', 74958),
 ('do', 54234),
 ("'s", 39705),
 ('and', 28918),
 ('i', 21905),
 ('can', 21762),
 ('best', 19972),
 ('have', 19410)]

In [16]:
# 각 단어의 품사 갯수를 센다.
df_pos_hum = {'pos': [pos[1] for pos in pos_list_hum]}
pandas_df_pos_hum = pd.DataFrame(data=df_pos_hum)
spark_df_pos_hum = spark.createDataFrame(pandas_df_pos_hum)

all_pos_hum = spark_df_pos_hum.rdd.map(lambda poslist: (poslist.pos, 1))
all_pos_counts_hum = all_pos_hum.reduceByKey(lambda a, b: a+b).sortBy(lambda r: -r[1])
all_pos_counts_hum.take(10)

[('NN', 1491738),
 ('IN', 802471),
 ('DT', 640931),
 ('JJ', 622474),
 ('NNS', 448529),
 ('.', 447444),
 ('VB', 316633),
 (',', 240613),
 ('VBZ', 206327),
 ('RB', 205344)]

In [17]:
WordCount_Hum = all_words_counts_hum.toDF().toPandas().rename(columns = {'_1':'Word', '_2':'Count'  })
WordCount_GPT = all_words_counts_gpt.toDF().toPandas().rename(columns = {'_1':'Word', '_2':'Count'  })
PosCount_Hum = all_pos_counts_hum.toDF().toPandas().rename(columns = {'_1':'Position', '_2':'Count'  })
PosCount_GPT = all_pos_counts_gpt.toDF().toPandas().rename(columns = {'_1':'Position', '_2':'Count'  })

In [18]:
WordCount_Hum

                  Word   Count
0                  the  201229
1                   be  140846
2                    a   74958
3                   do   54234
4                   's   39705
...                ...     ...
146024   appurtenances       1
146025            4:45       1
146026  post-operation       1
146027           dinah       1
146028            mots       1

[146029 rows x 2 columns]

In [19]:
WordCount_GPT

                   Word   Count
0                   the  126898
1                    be  120713
2                     a   57092
3                    's   35939
4                   you   24212
...                 ...     ...
112034       sisterhood       1
112035           confes       1
112036   mcnugget-sized       1
112037  thorning-schmid       1
112038             mots       1

[112039 rows x 2 columns]

In [20]:
PosCount_Hum

   Position    Count
0        NN  1491738
1        IN   802471
2        DT   640931
3        JJ   622474
4       NNS   448529
5         .   447444
6        VB   316633
7         ,   240613
8       VBZ   206327
9        RB   205344
10       CC   192349
11      VBD   189825
12      VBP   179235
13      VBN   165761
14       TO   156581
15      PRP   152645
16       CD   143735
17      VBG   120917
18      WRB   113836
19       MD    94966
20       WP    90486
21     PRP$    87568
22      WDT    70094
23      POS    38587
24      JJS    35031
25        (    30488
26        )    30445
27        :    28960
28       ''    25258
29       ``    19914
30      JJR    18304
31       RP    16300
32      NNP    13164
33       EX    10024
34      RBS     9341
35      RBR     9089
36       FW     4225
37        $     3796
38      PDT     2582
39      WP$      793
40        #      349
41       UH      343
42      SYM      258
43     NNPS      145
44       LS        3

from matplotlib import pyplot as plt
PosCount_Hum['Count'].plot(kind='hist', bins=20, title='Count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
PosCount_Hum['Count'].plot(kind='line', figsize=(8, 4), title='Count')
plt.gca().spines[['top', 'right']].set_visible(False)

In [21]:
PosCount_GPT

   Position    Count
0        NN  1068050
1        IN   575562
2        DT   507743
3        JJ   423269
4       NNS   304373
5         .   278256
6        VB   205065
7       VBZ   176750
8        TO   136835
9       VBN   110508
10      VBP   107824
11      VBG   102834
12      PRP    97627
13       WP    97082
14      VBD    96883
15       CC    86675
16       RB    74784
17       CD    73985
18      WDT    70665
19     PRP$    69046
20       MD    68599
21      POS    38493
22      WRB    30136
23      RBS    13482
24      JJS    11968
25       ''    11944
26       ``    11369
27        (     8241
28      JJR     7770
29        )     7007
30       EX     6471
31       RP     6458
32      NNP     4406
33      RBR     3685
34        :     3311
35        $     2266
36       FW     1186
37      PDT      924
38        ,      696
39        #      204
40      WP$       91
41     NNPS       77
42      SYM       44
43       UH       26
44       LS        3

from matplotlib import pyplot as plt
PosCount_GPT['Count'].plot(kind='hist', bins=20, title='Count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
PosCount_GPT['Count'].plot(kind='line', figsize=(8, 4), title='Count')
plt.gca().spines[['top', 'right']].set_visible(False)